/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distribution_system;

import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Kazu
 */
public class Main_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Main_Dashboard
     */
    public Main_Dashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ReportButton = new javax.swing.JButton();
        DistributionButton = new javax.swing.JButton();
        DonationButton = new javax.swing.JButton();
        ResidentButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BALAYAN CENTER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        ReportButton.setText("VIEW REPORTS");
        ReportButton.setPreferredSize(new java.awt.Dimension(150, 50));
        ReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        DistributionButton.setText("MANAGE DISTRIBUTION");
        DistributionButton.setPreferredSize(new java.awt.Dimension(150, 50));
        DistributionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DistributionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        DonationButton.setText("MANAGE DONATION");
        DonationButton.setPreferredSize(new java.awt.Dimension(150, 50));
        DonationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DonationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        ResidentButton.setText("MANAGE RESIDENT");
        ResidentButton.setPreferredSize(new java.awt.Dimension(150, 50));
        ResidentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ResidentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        LogoutButton.setText("LOGOUT");
        LogoutButton.setPreferredSize(new java.awt.Dimension(150, 50));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 215, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DonationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonationButtonActionPerformed
        DonationFrame donation = new DonationFrame();
        donation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DonationButtonActionPerformed

    private void ResidentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentButtonActionPerformed
        ResidentFrame resident = new ResidentFrame();
        resident.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResidentButtonActionPerformed

    private void DistributionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributionButtonActionPerformed
        ReliefFrame relief = new ReliefFrame();
        relief.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DistributionButtonActionPerformed

    private void ReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButtonActionPerformed
        ReportAndLogs report = new ReportAndLogs();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DistributionButton;
    private javax.swing.JButton DonationButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ReportButton;
    private javax.swing.JButton ResidentButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
